### ISSUE TITLE
Tooltip target ref object type error issue.

### ISSUE THREAD

**Issue by ibodev1** [primefaces/primereact#8081]
https://github.com/primefaces/primereact/blob/df65082018dab08beadce356d81d93081f0aedb4/components/lib/tooltip/tooltip.d.ts#L110

error;

```
error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: TooltipProps): Tooltip', gave the following error.
    Type 'RefObject<HTMLParagraphElement | null>' is not assignable to type 'string | HTMLElement | string[] | RefObject<HTMLElement> | undefined'.
      Type 'RefObject<HTMLParagraphElement | null>' is not assignable to type 'RefObject<HTMLElement>'.
        Type 'HTMLParagraphElement | null' is not assignable to type 'HTMLElement'.
          Type 'null' is not assignable to type 'HTMLElement'.
```

code;

```tsx
  const anyTemplate = (data: anyData) => {
    const anyRef = useRef<HTMLParagraphElement | null>(null);

    return (
      <div className="max-w-xs overflow-hidden">
        <Tooltip target={anyRef} position="top" showDelay={400} content={...} />
        <p className="truncate" title={...} ref={anyRef}>
         ...
        </p>
      </div>
    );
  };
```

After upgrading the primereact version to v10.9.6, the tooltip started to give a type error in the components I used as target. the reason for the error is that the referenced component is nullable. since I gave null instead of html element as default value, the reference is mutable ref object and the target type is expected from the ref object type of the html element that is not flat null.

@types/react;

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0be319a855105188f05c0196a991e2465014244e/types/react/index.d.ts#L1728

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0be319a855105188f05c0196a991e2465014244e/types/react/v18/index.d.ts#L1993

proposed change in code;

```tsx
target?: string | string[] | HTMLElement | React.RefObject<HTMLElement> | React.RefObject<HTMLElement | null> | undefined;
```

react v18 use ref mutable object;

```tsx
React.MutableRefObject<HTMLElement> | React.MutableRefObject<HTMLElement | null>
```

**Comment by ibodev1** [comment]
@melloware may be of interest to you.

**Comment by ibodev1** [comment]
this was a problem caused by me. i am closing this issue. but it would still be good to add the mutable ref object type in the target property in v11. happy coding!
