### ISSUE TITLE
InputText: Typescript useRef types with new const instead of class components

### ISSUE THREAD

**Issue by dvpritzbuer** [primefaces/primereact#6336]
### Describe the bug

`const ref = useRef<Stepper>(null);` --> "'Stepper' refers to a value, but is being used as a type here. Did you mean 'typeof Stepper'?"

`const ref = useRef<Panel>(null);` --> works fine

### Reproducer

https://stackblitz.com/edit/vitejs-vite-osrp8p?file=src%2FApp.tsx,package.json

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
@dvpritzbuer can you wait until the next release I am pretty sure all of your issues you are reporting are already fixed.

**Comment by dvpritzbuer** [comment]
I mean my first issue today was not already fixed and why shouldn't you take my free feedback even if you just tag it with fixed in 10.6.3? 

And this issue here is valid for all new components that use const instead of class (also tested it for IconField) and not only the Stepper!

But ok.. at least in short notice my other bugs as comment:
- IconField export/import wrong ("primereact/iconfield/iconfield")
- Stepper documentation example and stackblitz use wrong imports (@/components/lib... instead of primereact/) 
- InputIcon documentation example uses vue code instead of react

**Comment by melloware** [comment]
IconField already fixed: https://github.com/primefaces/primereact/pull/6271

What I was saying was in `main` many things have already been fixed related to Stepper, InputIcon, IconField.

**Comment by dvpritzbuer** [comment]
Yeah that's fine, but it's a lot easier for me to just post an issue report instead of searching the code for possible fixes.
Maybe a rough estimate when 10.6.3 will release?

**Comment by melloware** [comment]
i think this week sometime.  I don't work for PrimeTek...

**Comment by gucal** [comment]
Hi,

With release 10.6.3 the issue should be fixed. If you notice that the issue persists, please ping me.

**Comment by dvpritzbuer** [comment]
This error is not fixed - updated the linked stackblitz.

Also I recognized the original ticket description is not correct since Stepper doesn't have a ref and I just tested it initially with this component since this is a new const type definition. 
The stackblitz is now based on InputText.

I have no perfect solution here for you since it would either require the user to write more code or to import another type.

But it would work with this line:
`const inputRef2 = useRef<React.ElementRef<typeof InputText>>(null);`

So either the user always writes this line himself if using refs within typescript or you export another type like `export const type InputTextRef = React.ElementRef<typeof InputText>;` and the user has to use this new type then.

Maybe you find a better solution here?

**Comment by melloware** [comment]
Reopened and changed the title.

**Comment by dvpritzbuer** [comment]
Ah sorry, I got confused by changing the types within PR [#6356](https://github.com/primefaces/primereact/pull/6356) and Stepper not having any ref definition yet, but of course the Stepper also has a ref and the initial title was valid 😅

**Comment by melloware** [comment]
@dvpritzbuer i am confused where are we at with this ticket as of 10.6.5?

**Comment by dvpritzbuer** [comment]
@melloware sry for my late response, but I guess the problem is not fixed and my last response is still valid:

> I have no perfect solution here for you since it would either require the user to write more code or to import another type.
But it would work with this line:
const inputRef2 = useRef<React.ElementRef<typeof InputText>>(null);
So either the user always writes this line himself if using refs within typescript or you export another type like export const type InputTextRef = React.ElementRef<typeof InputText>; and the user has to use this new type then.
Maybe you find a better solution here?

**Comment by bloodykheeng** [comment]
hello @melloware was this sorted seems am getting it

**Comment by melloware** [comment]
You can see on the right of this ticket @bloodykheeng its fixed in 10.9.3 which is not out yet.

**Comment by jh-aimpera** [comment]
@melloware After the update to 10.9.3 I have problems with the stepper component. 

I get this error:
 `Property children does not exist on type
IntrinsicAttributes & IntrinsicClassAttributes<Stepper> & Readonly<StepperProps>`

The stepper stackblitz demo shows the same:
https://stackblitz.com/run?file=src%2FApp.tsx

Any insights here?

**Comment by melloware** [comment]
Yep fixed for 10.9.4...

**Comment by jh-aimpera** [comment]
> Yep fixed for 10.9.4...

Great! Thanks!

**Comment by jh-aimpera** [comment]
> [@melloware](https://github.com/melloware) is 10.9.4 out yet ?

you can see the latest version on the github project page:

![Image](https://github.com/user-attachments/assets/2ef64086-24fa-4612-9ac1-f4f5256769ab)

**Comment by bloodykheeng** [comment]
so as we wait for 10.9.4 what quick work around can i use cos seems setter is not allowing childeren
am using primereact 10.9.3

```
  // stepper
  const stepperRef = useRef<Stepper>(null);


```

**Comment by jh-aimpera** [comment]
> do u have a work around for 10.9.3

My work around is using 10.9.2 in the meantime

**Comment by bloodykheeng** [comment]
yah me too in 10.9.2 i had used any and it was working but ive notted it doesnt work in 10.9.3

**Comment by bloodykheeng** [comment]
i think in 10.9.3 the solution is to ignore the the typescript warnig 😆😆😆😆 cos its wrong lol noway the component doesnt take in children

 {/* @ts-ignore */}
        <Stepper ref={stepperRef} pt={{ root: "w-full md:w-[50rem]", panelContainer: "surface-0 border-round shadow-2" }} linear={true} >
