### PR TITLE
Fix #6334: typescript definition for Stepper and StepperPanel

### LINKED ISSUE #6334: StepperPanel: New const instead of class components are no valid JSX.Element's
### Describe the bug

"JSX element type 'Stepper' does not have any construct or call signatures."

"ERROR(TypeScript)  'StepperPanel' cannot be used as a JSX component.
  Its type 'Component<StepperPanelProps, any, any>' is not a valid JSX element type."

### Reproducer

https://stackblitz.com/edit/vitejs-vite-9mym3z?file=src%2FApp.tsx,package.json

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by dvpritzbuer**
Fix #6334: typescript definition for Stepper and StepperPanel

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@gucal @nitrogenous @mertsincan did we not use `React.PropsWithChildren` because its React 18 only and we wanted to be backward compatible with React 17?  https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc

Is that why we declare children in most components like this:

```ts
    /**
     * Used to get the child elements of the component.
     * @readonly
     */
    children?: React.ReactNode | undefined;
```

??

**Comment by dvpritzbuer** [comment]
@melloware 
seems to work fine with react 17.0.2 - here is a stackblitz example: https://stackblitz.com/edit/vitejs-vite-9iwtma?file=src%2FApp.tsx

**Comment by melloware** [comment]
nice!

**Comment by dvpritzbuer** [comment]
I've recognized the Stepper does have a ref property and was missing the definition for that.

Updated the branch with a proposed solution. I'm not sure about naming and the documentation part, but at least you have a general example of how the typing could work with the ref and custom methods.

**Review by melloware — APPROVED** [review]

**Comment by sancelot** [comment]
Hi, 

I have had this error, I think it is related, but I am unable to tell it is "normal" or a "mistake" somewhere in typings ?

error TS2749: 'Stepper' refers to a value, but is being used as a type here. Did you mean 'typeof Stepper'?
const stepperRef = useRef<Stepper|null>(null);

**Comment by melloware** [comment]
No @sancelot the typing of this compoennt looks wrong and weird to me. I can reproduce it right here @dvpritzbuer see: https://stackblitz.com/edit/gwed3brm?file=src%2FApp.tsx

**Comment by dvpritzbuer** [comment]
@melloware yeah this bug was already known as this PR here was created, I created this issue for that: https://github.com/primefaces/primereact/issues/6336

**Comment by melloware** [comment]
Thank you. I see the issue these are declared differently than all other components I am not quite sure why.
