### ISSUE TITLE
Failed to compile after upgrading primereact from 2.0.0 to 3.0.0

### ISSUE THREAD

**Issue by qmn1711** [primefaces/primereact#752]
This is error message after I upgrade from 2.0.0 to 3.0.0

> Failed to compile
> Type error: Type '{ children: (false | Element)[]; visible: boolean; showHeader: false; width: string; modal: true; onHide: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Dialog> & Readonly<{ children?: ReactNode; }> & Readonly<DialogProps>'.
  Property 'width' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Dialog> & Readonly<{ children?: ReactNode; }> & Readonly<DialogProps>'.  TS2322

My package.json:
`react: 16.7.0-alpha.2`
`react-dom: 16.7.0-alpha.2`
`@types/react: 16.7.17`
`@types/react-dom: 16.0.11`
