### ISSUE TITLE
primereact 9.1.0 it is not loaded using vite

### ISSUE THREAD

**Issue by myset** [primefaces/primereact#4064]
### Describe the feature you would like to see added

When I'm using Vite with primereact version 9.0.0 works and with 9.1.0 doesn't

It fail with

`error TS2307: Cannot find module 'primereact/api' or its corresponding type declarations.`

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Go back to primereact 9.0.0

**Comment by melloware** [comment]
Assigned to PrimeTek to review.

**Comment by melloware** [comment]
I am having errors in CRA too.

**Comment by mertsincan** [comment]
@myset @melloware Could you please try it with 9.1.1 ?

**Comment by myset** [comment]
Everything works well with 9.1.1

Keep up the good work, PRIME team  !!

**Comment by melloware** [comment]
Agreed all fixed on CRA too.
